version: "3.9"
services:
    backend:
        build: .
        depends_on:
            - database

    database:
        image: postgres:13.1
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=challenge
            - POSTGRES_PASSWORD=123qweQWE
            - POSTGRES_DB=challenge

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - database
