version: "3.9"
services:
    backend:
        build: .
        command: flask run --host="0.0.0.0"
        environment:
            - FLASK_APP=src/Infraestructure/Web/Flask/wsgi.py
            - FLASK_ENV=development
            - FLASK_DEBUG=1
            - PYTHONPATH=/code/src
        ports:
            - 5000:5000
        volumes:
            - .:/code
        depends_on:
            - database

    database:
        image: postgres:13.1
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=challenge
            - POSTGRES_PASSWORD=123qweQWE
            - POSTGRES_DB=challenge

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - database
