export class TeamMemberDTO {
    id: string = ''
    active_mt: number = 0
    current_team: string = ''
    date_start_team: string = ''
    available_ops: number = 0
    email: string = ''
    english: number = 0
    full_name: string = ''
    link_cv: string = ''
    location: string = ''
    main_1: string = ''
    main_1_score: number = 0
    main_2: string = ''
    main_2_score: number = 0
    next_team: string = ''
    next_tech_secondary: string = ''
    notes: string = ''
    role: string = ''
    secondary_1: string = ''
    secondary_1_score: number = 0
    secondary_2: string = ''
    secondary_2_score: number = 0
    secondary_3: string = ''
    secondary_3_score: number = 0
    target_tech_main: string = ''
    techSkill: string = ''
}